trigger:
 - main
pool: omkarwipropool

stages:
 - stage: install
   jobs:
    - job : terraforminstall
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
 - stage: init
   jobs:
   - job: init
     steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
         backendAzureRmStorageAccountName: 'omkarst345'
         backendAzureRmContainerName: 'tfstate'
         backendAzureRmKey: 'dev.todoapp.tfstate'
      

