
trigger:
- main

pool: omkarwipropool
 
stages:
 - stage: install
   jobs:
    - job : install
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
    - job: init
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
          backendServiceArm: 'omkarwiprosc'
          backendAzureRmResourceGroupName: 'omkarrg'
          backendAzureRmStorageAccountName: 'omkarst345'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'dev.todoapp.tfstate'
       
      

       
