trigger:
 - main
pool: omkarwipropool

stages:   
 - stage: install
   jobs:
   - job: install
     steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'  
 - stage: init
   jobs:
   - job: init
     steps:    
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
         backendServiceArm: 'omkarnsc'
         backendAzureRmStorageAccountName: 'omkarst3455'
         backendAzureRmContainerName: 'tfstate'
         backendAzureRmKey: 'dev.todoapp.tfstate'
 - stage : fmtplan
   jobs:  
    - job: fmtplan
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
          environmentServiceNameAzureRM: 'omkarnsc'
      


